# Generated by Django 4.0.4 on 2022-05-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):



    operations = [

        migrations.AddField(
            model_name='shift',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='period_viewer.shop'),
        ),
    ]
